apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring-system
spec:
  releaseName: metrics-server
  chart:
    repository: https://charts.helm.sh/stable
    name: metrics-server
    version: 2.8.8
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP
